### ISSUE TITLE
data definition Vs. theoretical model

### ISSUE THREAD

**Issue by deemaalomair1** [best-zhang-zhi/CAS741Project#10]
hello 

I think Velocity and Acceleration should be under data definition not theoretical model .. because they are basic rule you will use to develop your project + they are not driven from other rule.

**Comment by smiths** [comment]
@best-zhang-zhi, I agree with @deemaalomair1.  A TM should be refined by a GD or IM, or it isn't really a TM.  I see your velocity and acceleration list DDs that reference these TMs, but when I looked into it, they don't actually use these TMs.

**Comment by smiths** [comment]
@best-zhang-zhi, I have looked closer at your document, and I've changed my mind.  I believe I now see what you are trying to do, but without including derivations, the connections between the TMs and DDs is not clear.  You need to add derivations to your documentation.  You can do this either in the Description field, or in a section you introduce below the definition.  (There are examples of Detailed Derivations in the examples we have discussed in class.)

You can keep T2 and T3 as theoretical models.  You can keep DD1 to DD4 as data definitions.  (You should add text to the description explaining where these formulas come from.  You need to make an explicit connection between your Figure 1 and these formulas.)

DD5 should become GD1.  You are refining your T2.  You show this by showing the derivation:

v = dx/dt from T2
substitute in x1 from DD1
v = d(L1*sin(theta1))/dt
apply the chain rule and then get the equation you have for DD5 (which should be GD1 going forward)

Your TM2 is now explicitly referenced in the derivation of DD5.  Previously this reference was implicit, and that isn't an option.  All references have to be explicit.

Similar reasoning applies for DD6-DD8.  DD9 to DD12 will also become GDs.  In this case you are refining your definition of acceleration (T3).

**Comment by Zhang-Zhi-ZZ** [comment]
@smiths  Thank you for your advice. I have changed DD5-12 to GDs in commit: 12af313230ba8e3cb237f7b54fb7f40567369e28. And I'm still working on the derivations.

**Comment by smiths** [comment]
@best-zhang-zhi, you shouldn't really close this issue until you have done all of the parts, including the derivations.  If you want to close this issue, but create a new issue devoted to completing the derivations, that would be fine.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith,

I have added derivations for all GDs in commit: 7e2e630b7af4ffe604f84f386d8765c88dc394e8. 
And I will do the derivations for IM soon. 
Thank you!

**Comment by smiths** [comment]
Thank you @best-zhang-zhi.
