### ISSUE TITLE
IM1 & IM2 have the same label 

### ISSUE THREAD

**Issue by deemaalomair1** [best-zhang-zhi/CAS741Project#11]
Hello

both instance model 1 and 2 have the same label "calOfForceOnTopPendulum" , but they have different equation and output.  I think you meant "calOfForceOnBottumPendulum" for the second IM.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Deema, thank you for pointing this out! It has been fixed in commit 07bc67b4f043492df6d9eeab27309b06a81a35c2
