### ISSUE TITLE
functional requirement 1 

### ISSUE THREAD

**Issue by deemaalomair1** [best-zhang-zhi/CAS741Project#12]
hello

i did not get what you mean by the first functional requirement:

R1: Input the values from

**Comment by smiths** [comment]
I noticed this too @deemaalomair1.  @zhzhzi, you probably meant to include a reference to your Table 4.

**Comment by Zhang-Zhi-ZZ** [comment]
Hey Deema, I updated it in commit: 0b441aaff56bc025b5ee824d2f358091fb18edd2.

Thank you!
