### ISSUE TITLE
Please add the .gitignore file

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#13]
Please add the .gitignore file to your repo.  You can see a sample .gitignore file at:

https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/BlankProjectTemplate/docs/.gitignore

When you close this issue, please include the commit number (hash) that closes the issue.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith,

I have added the .gitignore file to my repo in commit ed0eeac1b8dc1388add7074aadcfb2f0f4f93c61

**Comment by smiths** [comment]
@best-zhang-zhi, the file should not have a "name", just an "extension."  The full filename should be `.gitignore`.  As you have it, the file does not work as intended.  (If you do not understand the purpose of .gitignore, please google it.)

**Comment by caobo1994** [comment]
Furthermore, the file shall be put at the root directory of the whole git repo.

Sent from Mail for Windows 10

**Comment by Zhang-Zhi-ZZ** [comment]
@smiths  
I updated the .gitignore file in commit 6d4493f6a21821d82b6bec04f7bb439ac951ca15

Is this what you meant?

**Comment by Zhang-Zhi-ZZ** [comment]
@smiths  Hi Dr.Smith, I did some small modification to .gitignore file in commit: 0b441aaff56bc025b5ee824d2f358091fb18edd2. 
Before, I had to manually remove other files generated by latex, but now, it automatically ignores files other than .tex and .pdf. Thank you!

**Comment by smiths** [comment]
Great!
