### ISSUE TITLE
Comments.tex

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#15]
Please add the file, and an include for `Comments.tex`:

https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/BlankProjectTemplate/docs/Comments.tex

This file is supposed to be in your repo, as it is in `BlankProjectTemplate`, so that I can easily add comments to your work.  I can often provide quicker and more detailed feedback if I type it directly into your `SRS.tex` file.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith, 
I have included the comments in my file, not sure if this is what you meant. 
2d07ed058c917745907ff13c64aab5d23b27595f

**Comment by caobo1994** [comment]
I think you should add .tex to file names in \input.

**Comment by best-zhang-zhi** [comment]
@caobo1994  where is \input?

**Comment by Zhang-Zhi-ZZ** [comment]
@caobo1994  
Do you mean 
\input{../Comments.tex}
\input{../Common.tex}
?

**Comment by caobo1994** [comment]
\input{Comments} shall be \input{Comments.tex}, and same for the other one.

Sent from Mail for Windows 10

**Comment by Zhang-Zhi-ZZ** [comment]
@caobo1994  Great! Thank you! I did it in commit 3ba676ed96933c649fa34cf15dff63b9bb0fbb5e
