### ISSUE TITLE
Update the units for g

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#16]
Acceleration is written with the units m/s^2.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith,

I double checked my SRS, and I'm not sure what you mean. 
<img width="436" alt="Screen Shot 2019-10-30 at 12 31 26 AM" src="https://user-images.githubusercontent.com/55267358/67829193-afaa4000-faac-11e9-8820-e4dfa693f38c.png">
Isn't this correct?

**Comment by smiths** [comment]
Your units for g (gravitational constant) are listed as N/kg.  The units should be listed as m/s^2.  Also, you should call it "acceleration due to gravity."  The gravitational constant is something else.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith, this has been fixed in commit 99f7a8e1f5e50752b4b1dd60f905e9ae5965adee

Thank you!!
