### ISSUE TITLE
Figure 1 should match your assumptions

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#19]
Your Figure 1 should match the assumptions listed.  In particular, the coordinate system shown should match your assumptions.

**Comment by Zhang-Zhi-ZZ** [comment]
The figure had been updated in commit: 8bdcd4f8c0f1e00304028e809669f49cee65e055. Thank you!

**Comment by smiths** [comment]
I'm sorry @best-zhang-zhi, your assumption A3 says that the y-axis is opposite to gravity, but your Figure shows them in the same direction (down).  You are also missing an assumption that will make the direction of the x axis unambiguous.  (You could add an assumption for a right handed coordinate system.)

**Comment by Zhang-Zhi-ZZ** [comment]
Dear Dr. Smith,

The figure is updated in commit 77bfef5343af57a484d42dc30d15123a009c9c86, sorry I draw the wrong direction for y axis. 

And I added the assumption for right handed coordinate system in commit b40cf4177ee578ea03d51fac4e43e68e73c50087.

**Comment by smiths** [comment]
Thank you @best-zhang-zhi.
