### ISSUE TITLE
Table of symbols 

### ISSUE THREAD

**Issue by deemaalomair1** [best-zhang-zhi/CAS741Project#2]
Hello Zhi Zhang,

In the table of symbols you wrote:
X1 : horizontal position of the top pendulum
X2 : horizontal position of the top pendulum
Y1 : vertical position of the bottom pendulum
Y2 : vertical position of the bottom pendulum
should X2 be the horizontal position of the bottom pendulum? and y1 be vertical position of the top pendulum?

**Comment by Zhang-Zhi-ZZ** [comment]
Hello Deema,
Thank you for pointing out this, I really appreciate it! My SRS is not finished yet, and I will submit the final version of it by Friday 11:59pm.

**Comment by smiths** [comment]
As mentioned in #3, you want to include the commit hash that closes the issue, and  you want to close the issue.  :smile:

**Comment by smiths** [comment]
@best-zhang-zhi, you did half of what I was looking for.  😄   What commit hash closed the original issue?  You want to get in the habit of doing this, so that your issues have traceability.   You want others to be able to judge whether the fix adequately addresses the original issue.

**Comment by Zhang-Zhi-ZZ** [comment]
@smiths  Hi Dr. Smith, I just asked Bo what you meant by commit hash, and now I know it!  I have a class this afternoon, will try to fix all the issues today, and I will remember to add the commit hash!

**Comment by smiths** [comment]
Sounds good @best-zhang-zhi.  I'm glad that @caobo1994 could assist you.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi, 
this problem has been fix in commit https://github.com/best-zhang-zhi/CAS741Project/commit/b5542c013f2acc3509f70e2eab70fce4fee021d9

**Comment by smiths** [comment]
Thank you @best-zhang-zhi.  The change your commit points to is a change in the pdf file.  This is probably a consequence of still learning how to best use a version control system.  Going forward though, please point to the commit where the tex file was changed (in addition to the pdf file is fine).
