### ISSUE TITLE
Redo your list of assumptions

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#21]
There are reuse errors in your list of assumptions.  Your problem is the double pendulum, not projectile motion.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith, 
I have updated the list of assumptions in commit: ad0c1844fe0e932274e39220fcb76a793a9e0866. 

And I'm currently working on the DDs, TMs, GDs. I hope I could figure these out by myself. But I may need to book an appointment with you to discuss about it. Thank you!

**Comment by smiths** [comment]
@best-zhang-zhi, if you have questions, we can certainly have a meeting.  Just let me know.
