### ISSUE TITLE
F = m*a should be F = ma

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#22]
LaTeX formats so that multiplication is show by writing variables side by side.  You do not need the `*` in the `F = m*a` formula.  You can just write `$F = ma$` in your LaTeX.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith,

It has been fixed in commit 5f3aaf8dd07fb91490de386e9deedb5db1f8a60c. 
Thank you!

**Comment by smiths** [comment]
Looks good.
