### ISSUE TITLE
IM1 and IM2 should be GDs

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#24]
IM1 and IM2 are intermediate steps toward your actual goal.  The IMs should be referenced by the requirements, and IM1 and IM2 on their own don't do anything.  They are an intermediate step toward IM3.  You really only need IM3 (relabelled IM1).  You should also explain the derivation of IM3 from IM1 and IM2 (relabelled as GDs).

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith,

the derivation of IM1(old IM3) is added in commit: 7ecebd98861a9e69bb58039df8ed4f3065c01ebb

Thank you!
