### ISSUE TITLE
T1 and T2

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#25]
You need to introduce T1 and T2 (tensions in the rods).  For IM1 and IM2 you need to explain the derivation of these equations.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith,

In the formulas i'm referencing, the tension of rods will be cancelled out in calculating the movement of the rods, the url of my reference is: https://www.myphysicslab.com/pendulum/double-pendulum-en.html. 

I don't see there's need to calculate the tension, should I still introduce the formulas for calculating the tensions?

**Comment by smiths** [comment]
@best-zhang-zhi, when I say introduce T1 and T2, I am referring to defining these terms.  Just having a symbol in the table of contents is not enough.  You need to describe each symbol in the body of the document.  I am not asking for a formula for T1 or T1, I'm asking for a derivation of the equations that are given.  You are using Newton's second law (your T1), but you don't point this out to the reader.  The equation is just given.  You need to explain where it comes from.  The easiest way to do this is to derive the equation.  In the derivations, you will need to reference the other chunks of information.  This is where your traceability information comes into the document.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith,

I added derivation in commit: 87791d7f5b28056311d863666b87e63d88e7053c 

I added the free body diagram to introduce T1, T2. Please let me know this is good. Thank you!

**Comment by smiths** [comment]
Thank you.
