### ISSUE TITLE
Title unfinished

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#29]
The title of your SystVnV is
> Project Title: System Verification and Validation Plan for Double Pendulum

The *Project Title* shall be replaced with the real project title, which shall be done in docs/Common.tex.

**Comment by Zhang-Zhi-ZZ** [comment]
What do you mean? My project title is Double Pendulum

**Comment by caobo1994** [comment]
I think it shall be Double Pendulum: ... or just delete Project title.

best-zhang-zhi <notifications@github.com> 于 2019年11月12日周二 19:37写道：

**Comment by Zhang-Zhi-ZZ** [comment]
Oh yes! Thank you! It has been fixed in commit a48b4af6f4fdb89dac71701fbc7932179d20cb6b. Thank you!
