### ISSUE TITLE
Physical constraints: Both $\theta_1$ and $\theta_2$ are not zero.

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#30]
This constraint is too much for the intention, which is to make both masses move, However, when $\theta_1 \neq 0$ but $\theta_2=0$, the two masses will still move.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Bo, I removed this constraint from my SRS and systemVnV in commit: cd027ebe93ec420296b8e29b473250cba2d40fde. Thank you!
