### ISSUE TITLE
Test for non-positive parameter error: Not enough coverage

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#31]
I see that in a few tests, you intend to test that when the program is requiring a positive parameter, but given a non-positive one, the required error message shall be given. 

Furthermore, each test is for two parameters, and one of them is negative, and the other is 0.

However, it might be hard or even impossible to tell the error message is the result of which parameter. Also, popular practice is that the program will stop and report error when the first one is met. Thus, the program will only detect the first wrong parameter, and the second one is neither found nor tested.

I suggest that you break each test into two.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Bo, I have updated the test cases in commit: 21c6d99b85db58594a2f0c0fe5915ebe55b94499 where I added more test cases.
