### ISSUE TITLE
Correct output test

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#32]
In the *Correct Output* test, you ask the tester to manually compare two graphs. However, people's comparison of graphs are not always replicable, since two different people might give two different results due to different minimum discernible error by people.

Maybe this test is better based on data and computer comparison.

**Comment by Zhang-Zhi-ZZ** [comment]
This has been updated in commit 21c6d99b85db58594a2f0c0fe5915ebe55b94499.
