### ISSUE TITLE
About the definition of code walkthrough

### ISSUE THREAD

**Issue by sharyuwu** [best-zhang-zhi/CAS741Project#34]
I feel your description of the implementation of the code walkthrough does not really match the definition.
The definition of a code walkthrough should be the author holds a meeting and then the reviewers attend, etc.
More detail information can be found on this website. https://www.tutorialspoint.com/software_testing_dictionary/code_walkthrough.htm

![image](https://user-images.githubusercontent.com/55363335/68988887-99221980-080c-11ea-9094-66e3ca961afc.png)

**Comment by Zhang-Zhi-ZZ** [comment]
this has been fixed in commit: 21c6d99b85db58594a2f0c0fe5915ebe55b94499.
