### ISSUE TITLE
Suggestion: enhance the test case

### ISSUE THREAD

**Issue by sharyuwu** [best-zhang-zhi/CAS741Project#35]
According to the table of the input variable, the constraint is m1,m2> 0, I suggest you should also test when the m1 is 0, and m2 is 0 where either m1 or m2 is 0, should the error message pop up.

![image](https://user-images.githubusercontent.com/55363335/68988937-72181780-080d-11ea-91ea-d9d011a8b4d6.png)

**Comment by sharyuwu** [comment]
I just notice that you have set m2 = 0.
Then maybe you can do two cases where one is m1 is 0 and another one is m2 is 0.

**Comment by Zhang-Zhi-ZZ** [comment]
The test cases are updated in commit 21c6d99b85db58594a2f0c0fe5915ebe55b94499
