### ISSUE TITLE
Suggestion: enhance the definition of the output file

### ISSUE THREAD

**Issue by sharyuwu** [best-zhang-zhi/CAS741Project#36]
I suggest that giving more information about this "output file" like the type of the file(.text, .tex,.. etc), the name of the file, the path of the file, the content of the file.. etc. 

![image](https://user-images.githubusercontent.com/55363335/68989037-3716e380-080f-11ea-9f08-fece043da7be.png)

**Comment by Zhang-Zhi-ZZ** [comment]
This have been updated in commit 3930ec2602bded706697e4bd0b9ed4616e445781.
