### ISSUE TITLE
Suggestion: Check the invalid situation of the Graphic generator

### ISSUE THREAD

**Issue by sharyuwu** [best-zhang-zhi/CAS741Project#37]
You have tested the valid case of the Graphic generator. I think it will be nice if you can test the invalid case, which is users press the graphic bottom when the output file has not been generated. 

The image shows the valid case of the Graphic generator.
![image](https://user-images.githubusercontent.com/55363335/68989123-6b3ed400-0810-11ea-9f8b-c74f7f748735.png)

**Comment by Zhang-Zhi-ZZ** [comment]
I think if the generation of output file is being tested in Correct Output test, if there's no output file, there will be no output.
