### ISSUE TITLE
Suggest: the statement of maintainability

### ISSUE THREAD

**Issue by sharyuwu** [best-zhang-zhi/CAS741Project#38]
I think the input and the output statement of the maintainability do not related.
If you want to state maintainability as updating the document when there are changes, I suggest putting "Existing software" as the initial, "modified the software" as input/condition, and "update the software" as the output/result.

![image](https://user-images.githubusercontent.com/55363335/68998039-1b492700-087b-11ea-98c4-f7e7d7f7d1e8.png)

**Comment by sharyuwu** [comment]
And also when you state "update the software", you can put more detail information like update the table of traceability.. etc.

**Comment by Zhang-Zhi-ZZ** [comment]
This has been updated in commit 21c6d99b85db58594a2f0c0fe5915ebe55b94499. Thank you!
