### ISSUE TITLE
MG and MIS ready

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [best-zhang-zhi/CAS741Project#39]
Hi @smiths  @caobo1994  @Ao99 
My MG and MIS are ready! Here is the link to the docs: https://github.com/best-zhang-zhi/CAS741Project/tree/master/Double%20Pendulum/docs/Design

Thank you everyone for reviewing them!

**Comment by Ao99** [comment]
Submitted 5 issues.

**Comment by smiths** [comment]
MG reviewed - comments embedded in tex file in bb262d2.

**Comment by smiths** [comment]
MIS reviewed c3e444f.
