### ISSUE TITLE
Purpose of Document: Not really faking it.

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#4]
> The purpose of the document is to provide detailed requirements of the Double Pendulum project for co-workers(CAS 741 classmates and Dr.Spencer Smith) to better understand the project, and to provide planning dor the design stage.

The definition of co-workers are too specified on this class. To actually 'faking' it, a better group might be the people interested in the DP's behavior.

BTW, a small typo, dor->for.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Bo, 
Thanks for pointing this out!

**Comment by smiths** [comment]
@best-zhang-zhi, since you addressed the comment from @caobo1994, you can close this issue.  However, when you close it you should include the commit hash that includes your changes, so that someone can easily inspect your work.
