### ISSUE TITLE
AC2 and AC3: What is the difference between initial input data and input parameter?

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#41]
Both names are not so clear to me, and I do not understand their differences.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Bo, I copied it from SWHS doc, and in mt understanding, the format of the initial input data is like: .txt file, and the format of the input parameters will be something like: a list of values, for example, [1, 2, 3, 4], [2, 3, 4, 5].
