### ISSUE TITLE
M4: there might be a better way of saying it.

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#42]
I would say the following:
Secrets: calculates in accordance with theory ...
Service: calculates the acceleration of two angular coordinates from velocities.

**Comment by Zhang-Zhi-ZZ** [comment]
the acceleration equations module does not calculate anything, it just substitute the user inputs into a equation, for example, I have y = 3x+a, and I get user input for a to be 3, than the output will be y = 3x+3.
