### ISSUE TITLE
MIS page 11 - methods output

### ISSUE THREAD

**Issue by Ao99** [best-zhang-zhi/CAS741Project#47]
![image](https://user-images.githubusercontent.com/53056165/69836946-2fe1d380-121a-11ea-94c8-b1f0eb3d63bf.png)
According to the table, the outputs are functions. Does this function takes 1 parameter and produces 2 results?
It doesn't look like the output 
![image](https://user-images.githubusercontent.com/53056165/69836989-7a635000-121a-11ea-9a2e-01895157b0e6.png)

**Comment by Zhang-Zhi-ZZ** [comment]
no the function takes an equation, then output the integral of it.
