### ISSUE TITLE
MIS page 8 - verify_params()

### ISSUE THREAD

**Issue by Ao99** [best-zhang-zhi/CAS741Project#48]
Why t can't be 0? Would it be better to allow starting from t = 0?

Besides, t sometimes was written as T. Is it an inconsistency?

**Comment by Zhang-Zhi-ZZ** [comment]
Hi, this t here represents the time that user wants the double pendulum to perform, it's not the starting time, if it's 0, it mean the motion does not start, then there's no point of doing calculation. I changed the T to t in commit:3cb51341f6d50bfcd33d72508fd679fb1de84984. Thank you!
