### ISSUE TITLE
10.4.4 unclear meaning

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#49]
> with t_1 determined to be 0.05 second

I don't understand this term, since my first guess is 't_1=0.05s'. I think that my guess must be wrong mathematically and/or physically, but I don't find another way of understanding. Could you clear this up? Thanks!

**Comment by Zhang-Zhi-ZZ** [comment]
Hi, so I want to plot the diagrams of theta1(t), theta2(t), I just randomly selected 0.05s to be the time interval between each points.
