### ISSUE TITLE
Characteristics of Intended Reader: Lack requirements on Calculs.

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#5]
> The intended readers are expected to be knowledgeable about high school physics.

From later parts (such as User Characteristics), we know that this program involves solving of ODE, and requires knowledge of Calculus at least. Thus, ODE-related knowledge is missing here.

**Comment by Zhang-Zhi-ZZ** [comment]
The end user should have an understanding of high school Physics and Calculus, with knowledge of ordinary differential equations.

Do you think this will be better for User Characteristics section?

**Comment by caobo1994** [comment]
I guess not. I have talked to local students, and they say related Calculus knowledge is not covered in high school.

Never overestimate your reader's knowledge level.

**Comment by smiths** [comment]
There is a distinction between the intended reader's knowledge (section 2.3) and the user characteristics (section 3.2).  The reader needs to know more than the user.  This is a good example of this.  The reader of the document needs to understand ODEs, while the user doesn't necessarily need this knowledge.  @best-zhang-zhi, please update your intended reader characteristics.

**Comment by Zhang-Zhi-ZZ** [comment]
I have updated the intended reader characteristics in commit https://github.com/best-zhang-zhi/CAS741Project/commit/8f30c4ef136cad5aa118ec7702801dc26d0eed68. Please let me know if this is acceptable. 

Thank you!

**Comment by smiths** [comment]
Yes @best-zhang-zhi, the new reader characteristics look fine.
