### ISSUE TITLE
Output Module: filepath not clear.

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#50]
In this module, you mentioned that you intend to write the output to a 'file' named 'filename'. However, you did not assume the location of 'file'. I assume that the default place is some folder created by your project.

I think you might need to include the path somehow. Maybe 'filename' can include the path as well, while you specify that if the path is not given, the default path is somewhere.

**Comment by Zhang-Zhi-ZZ** [comment]
This has been updated in commit: 93b45050704c8a96d4d7a4573537bbd9ecd9f2ad. Thank you!
