### ISSUE TITLE
Input file format not clear

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#51]
Hi,
I have decided to use python3 as the implementing language.
When I implement the input parameter module, I find out that you have not specified the file format.
I have made a decision for you, and write a sample file in test/sample.yaml
I have also decided to use YAML as the input format. If you approve of this, please add pyyaml library as one of the dependencies.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Bo,
Why you choose to use YAML but not .txt? I haven't decided the input file format yet.

**Comment by caobo1994** [comment]
It is more human-friendly, and I am more familiar with it.

Besides, YAML files are basically text files, just with certain grammar rules.

You sounds like members of the committee in my Masters Defense. 

发件人: best-zhang-zhi
发送时间: 2019年12月11日 22:26
收件人: best-zhang-zhi/CAS741Project
抄送: Bo Cao; Author
主题: Re: [best-zhang-zhi/CAS741Project] Input file format not clear (#51)

Hi Bo,
Why you choose to use YAML but not .txt? I haven't decided the input file format yet.

**Comment by Zhang-Zhi-ZZ** [comment]
lol, I'm just wondering why YAML, because I don't know anything about YAML, but I googled it and found it to be very clear. I think I will use YAML.

**Comment by Zhang-Zhi-ZZ** [comment]
Thank you!
