### ISSUE TITLE
Add *.pyc to .gitignore

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#52]
Different people have different python versions and operating systems, so your .pyc files might not work on other's machines. Please exclude all *.pyc files from your git repo by adding them to the .gitignore file, and let each user generate those suitable to their systems.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Ao, it has been done in commit 0778829287abf1b07d726463d11351822fd33ce2
