### ISSUE TITLE
Goal Statement: Actual numbers might be of interest.

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#6]
In goal statement, you only intend to provide figures for these two angles. However, in my experience, some people might need actual data to further analyze it (like trying to find some kind of period, check whether the system's total energy is conserved, etc.), and it is easy to be done. You might want to consider adding a data output function to this program.

**Comment by smiths** [comment]
I agree completely with @caobo1994.  In fact, the goal should be to calculate the motion of the two masses, without mentioning graphs.  In the requirements there should be a requirement to output the results to a file, and a separate requirement to show the graphs.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi, 
I have changed the goal statement to be "calculate the motion of two masses", and I changed a little bit in the functional requirements, and the corresponding Traceability Matrices and Graphs in the commit https://github.com/best-zhang-zhi/CAS741Project/commit/177a9511e2fca1daceae2aed72137d3791e6a235. Thank you!!

**Comment by smiths** [comment]
@best-zhang-zhi, the changes look reasonable to me.
