### ISSUE TITLE
Comment on Assumption A3

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#8]
> A3: The direction of the y-axis is directly opposite to gravity.

We usually don't say this. Instead, we set the coordinate system first, then describe the physical properties based on it. 

Thus, if I were you, I would say 'The gravity takes the -y direction.'

**Comment by smiths** [comment]
I'm fine with either way of saying this.

**Comment by Zhang-Zhi-ZZ** [comment]
Thank you Bo, since i'm lazy, I will just remain it as it is.
