### ISSUE TITLE
Data definitions: separately define coordinate, velocity, and acceleration?

### ISSUE THREAD

**Issue by caobo1994** [best-zhang-zhi/CAS741Project#9]
In the data definition section, you define coordinate, velocity, and acceleration separately. However, the expressions of velocity and acceleration are derived from that of coordinate. Thus, in my opinion, only the dd of coordinate shall exist, while the definition of the other two shall be exchanged with those in theories.

**Comment by smiths** [comment]
@caobo1994, I think you might be noticing the same inconsistency between DDs, TMs and GDs that is discussed in #10.  In the discussion of that issue I have specific recommendations for rearranging the chunks.

**Comment by caobo1994** [comment]
@smiths, I agree with you, Sir. The solution in #10 has dealt with my findings in a slightly different way than I thought. 

I will close this issue by myself, if it is OK.

**Comment by smiths** [comment]
Agreed @caobo1994.
